-- =============================================================================
-- Maximo UC table + column comments
-- =============================================================================
-- Generated from scripts/maximo_comments.json. To regenerate, run:
--
--   python scripts/apply_uc_comments.py \
--     --comments-file scripts/maximo_comments.json \
--     --emit-sql scripts/apply_uc_comments.sql
--
-- HOW TO RUN:
--   1. Open this file in Databricks SQL Editor against the customer's warehouse.
--   2. Bind parameters: :catalog (e.g. eam) and :silver_schema (e.g. maximo_silver).
--   3. Review every statement with the customer.
--   4. Execute ONLY after explicit, unambiguous customer approval (per the
--      multi-checkpoint vetting flow in maximo-setup/SKILL.md §Optional).
--
-- This file modifies customer-owned Unity Catalog objects (table + column
-- comments). It must never run without explicit user approval.
-- =============================================================================

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WORKORDER') IS 'IBM Maximo work-order header. One row per WO holding CURRENT state. Status history is in WOSTATUS. Filter WOCLASS = ''WORKORDER'' for normal WOs (table also holds PM, CHANGE, RELEASE, ACTIVITY records).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WORKORDER') ALTER COLUMN `WONUM` COMMENT 'Business key — unique within SITEID, not globally.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WORKORDER') ALTER COLUMN `SITEID` COMMENT 'Site code. Always include in joins between Maximo tables — WONUM is unique only within a site.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WORKORDER') ALTER COLUMN `STATUS` COMMENT 'Current status. For history (transitions, time-in-state), use WOSTATUS.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WORKORDER') ALTER COLUMN `STATUSDATE` COMMENT 'When the current STATUS was set (not original create — use REPORTDATE for create time).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WORKORDER') ALTER COLUMN `WOCLASS` COMMENT 'Filter to ''WORKORDER'' for normal WOs. Other values: PM, CHANGE, RELEASE, ACTIVITY.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WORKORDER') ALTER COLUMN `WORKTYPE` COMMENT 'Customer-configured. Common: CM (corrective), PM (preventive), EM (emergency).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WORKORDER') ALTER COLUMN `ISTASK` COMMENT '1 = child task. Deduplicate to parent (PARENT column) for backlog counts.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WORKORDER') ALTER COLUMN `PARENT` COMMENT 'Parent WONUM if this is a child task (ISTASK=1) or sub-WO.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WORKORDER') ALTER COLUMN `ASSETNUM` COMMENT 'FK to ASSET (composite with SITEID).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WORKORDER') ALTER COLUMN `LOCATION` COMMENT 'FK to LOCATIONS (composite with SITEID).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WORKORDER') ALTER COLUMN `JPNUM` COMMENT 'FK to JOBPLAN (composite with ORGID).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WORKORDER') ALTER COLUMN `PMNUM` COMMENT 'FK to PM when this WO was generated by a PM.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WORKORDER') ALTER COLUMN `REPORTDATE` COMMENT 'When the WO was created/reported. Use this for backlog age, not STATUSDATE.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WORKORDER') ALTER COLUMN `ACTSTART` COMMENT 'Actual execution start.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WORKORDER') ALTER COLUMN `ACTFINISH` COMMENT 'Actual execution finish.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WORKORDER') ALTER COLUMN `SCHEDSTART` COMMENT 'Scheduled start window.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WORKORDER') ALTER COLUMN `SCHEDFINISH` COMMENT 'Scheduled finish window.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WORKORDER') ALTER COLUMN `FAILURECODE` COMMENT 'Top-level failure class code (FK to FAILURECODE table).';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WOSTATUS') IS 'Work-order status history — one row per status transition per WO. Required for ''time in status'' / ''transition path'' / ''who changed when'' questions. Note: REST-API status changes may NOT write to this table on classic Maximo 7.6 (see APAR IJ17261).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WOSTATUS') ALTER COLUMN `WONUM` COMMENT 'FK to WORKORDER.WONUM.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WOSTATUS') ALTER COLUMN `SITEID` COMMENT 'Composite with WONUM.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WOSTATUS') ALTER COLUMN `STATUS` COMMENT 'The status this transition represents.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WOSTATUS') ALTER COLUMN `CHANGEDATE` COMMENT 'When the transition was logged.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WOSTATUS') ALTER COLUMN `CHANGEBY` COMMENT 'User who made the change.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WOSTATUS') ALTER COLUMN `MEMO` COMMENT 'Optional free-text memo entered with the change.';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSET') IS 'Asset master. Join via ASSETNUM + SITEID (composite key).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSET') ALTER COLUMN `ASSETNUM` COMMENT 'Business key — unique within SITEID.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSET') ALTER COLUMN `SITEID` COMMENT 'Composite with ASSETNUM.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSET') ALTER COLUMN `DESCRIPTION` COMMENT 'Asset description (free text).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSET') ALTER COLUMN `CLASSSTRUCTUREID` COMMENT 'FK to CLASSSTRUCTURE — the asset class taxonomy.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSET') ALTER COLUMN `STATUS` COMMENT 'Current asset operational status.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSET') ALTER COLUMN `LOCATION` COMMENT 'Where the asset currently resides (FK to LOCATIONS).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSET') ALTER COLUMN `PARENT` COMMENT 'Parent asset (asset hierarchy).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSET') ALTER COLUMN `CRITICALITY` COMMENT 'Criticality score, customer-defined scale (commonly 1-5 or 1-10).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSET') ALTER COLUMN `INSTALLDATE` COMMENT 'When the asset was installed.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSET') ALTER COLUMN `MANUFACTURER` COMMENT 'Manufacturer code (FK to COMPANIES).';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSETMETER') IS 'Meter definitions per asset — corrosion thickness gauges, vibration channels, runtime hours, etc. Readings live in METERREADING. Meter type is a property of the METER definition, not stored here. Condition-monitoring warn/action limits live on MEASUREPOINT.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSETMETER') ALTER COLUMN `ASSETNUM` COMMENT 'FK to ASSET.ASSETNUM.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSETMETER') ALTER COLUMN `SITEID` COMMENT 'Composite with ASSETNUM.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSETMETER') ALTER COLUMN `METERNAME` COMMENT 'Meter identifier (e.g. UT_THICKNESS, VIB_VEL_HORIZ).';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.MEASUREPOINT') IS 'Condition-monitoring measurement points — per-asset meter points with warning/action limits that trigger PM or WO generation when breached. Readings flow in via METERREADING against the associated meter.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.MEASUREPOINT') ALTER COLUMN `ASSETNUM` COMMENT 'FK to ASSET.ASSETNUM.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.MEASUREPOINT') ALTER COLUMN `SITEID` COMMENT 'Composite with ASSETNUM.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.MEASUREPOINT') ALTER COLUMN `METERNAME` COMMENT 'FK to ASSETMETER — the meter this measurement point monitors.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.MEASUREPOINT') ALTER COLUMN `LOWERWARNING` COMMENT 'Low warning threshold.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.MEASUREPOINT') ALTER COLUMN `UPPERWARNING` COMMENT 'High warning threshold.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.MEASUREPOINT') ALTER COLUMN `LOWERACTION` COMMENT 'Low action threshold (triggers WO).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.MEASUREPOINT') ALTER COLUMN `UPPERACTION` COMMENT 'High action threshold (triggers WO).';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.METERREADING') IS 'Time-series meter readings against ASSETMETER. Append-only; ordered by READINGDATE.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.METERREADING') ALTER COLUMN `ASSETNUM` COMMENT 'FK to ASSET + ASSETMETER.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.METERREADING') ALTER COLUMN `SITEID` COMMENT 'Composite with ASSETNUM.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.METERREADING') ALTER COLUMN `METERNAME` COMMENT 'FK to ASSETMETER.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.METERREADING') ALTER COLUMN `READINGDATE` COMMENT 'When the reading was taken.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.METERREADING') ALTER COLUMN `READING` COMMENT 'The numeric reading value.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.METERREADING') ALTER COLUMN `READINGTYPE` COMMENT 'ACTUAL, DELTA, CHARACTERISTIC.';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LOCATIONS') IS 'Location master. Hierarchy traversal via LOCHIERARCHY table for multi-level structures.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LOCATIONS') ALTER COLUMN `LOCATION` COMMENT 'Business key — unique within SITEID.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LOCATIONS') ALTER COLUMN `SITEID` COMMENT 'Composite with LOCATION.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LOCATIONS') ALTER COLUMN `DESCRIPTION` COMMENT 'Free-text description.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LOCATIONS') ALTER COLUMN `TYPE` COMMENT 'Location type (OPERATING, STOREROOM, LABOR, COURIER, REPAIR, SALVAGE, VENDOR).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LOCATIONS') ALTER COLUMN `STATUS` COMMENT 'Active / inactive.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LOCATIONS') ALTER COLUMN `PARENT` COMMENT 'Immediate parent location.';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABTRANS') IS 'Labor transactions — one row per craft-hour booked to a WO. Aggregate to WO grain via WONUM + SITEID for actuals.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABTRANS') ALTER COLUMN `WONUM` COMMENT 'FK to WORKORDER.WONUM.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABTRANS') ALTER COLUMN `SITEID` COMMENT 'Composite with WONUM.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABTRANS') ALTER COLUMN `LABORCODE` COMMENT 'FK to LABOR.LABORCODE.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABTRANS') ALTER COLUMN `CRAFT` COMMENT 'Craft code (ELEC, MECH, INST, etc.).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABTRANS') ALTER COLUMN `STARTDATE` COMMENT 'Work start.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABTRANS') ALTER COLUMN `FINISHDATE` COMMENT 'Work finish.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABTRANS') ALTER COLUMN `REGULARHRS` COMMENT 'Regular hours booked.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABTRANS') ALTER COLUMN `PREMIUMPAYHOURS` COMMENT 'Overtime / premium hours.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABTRANS') ALTER COLUMN `LINECOST` COMMENT 'Cost of this transaction.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABTRANS') ALTER COLUMN `TRANSTYPE` COMMENT 'WORK, TRAVEL, etc.';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.PM') IS 'Preventive maintenance master — schedule and rules for generating WOs. PMSEQUENCE holds the step sequences.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.PM') ALTER COLUMN `PMNUM` COMMENT 'PM identifier.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.PM') ALTER COLUMN `SITEID` COMMENT 'Composite with PMNUM.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.PM') ALTER COLUMN `ASSETNUM` COMMENT 'Target asset (or LOCATION if asset-less).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.PM') ALTER COLUMN `JPNUM` COMMENT 'FK to JOBPLAN — the template used to generate WOs.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.PM') ALTER COLUMN `FREQUENCY` COMMENT 'Interval value.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.PM') ALTER COLUMN `FREQUNIT` COMMENT 'Interval unit (DAYS, HOURS, MILES, READINGS).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.PM') ALTER COLUMN `NEXTDATE` COMMENT 'Next due date.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.PM') ALTER COLUMN `LASTSTARTDATE` COMMENT 'Most recent generation.';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.FAILURECODE') IS 'Failure code taxonomy — a tree of PROBLEM, CAUSE, and REMEDY nodes. Aggregate by flattening to the level the user asked for.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.FAILURECODE') ALTER COLUMN `FAILURECODE` COMMENT 'Code identifier.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.FAILURECODE') ALTER COLUMN `DESCRIPTION` COMMENT 'Free-text description.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.FAILURECODE') ALTER COLUMN `PARENT` COMMENT 'Parent code in the tree.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.FAILURECODE') ALTER COLUMN `TYPE` COMMENT 'PROBLEM, CAUSE, or REMEDY.';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.FAILUREREPORT') IS 'Per-WO coded failure record. Created when a WO is closed with failure information.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.FAILUREREPORT') ALTER COLUMN `WONUM` COMMENT 'FK to WORKORDER.WONUM.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.FAILUREREPORT') ALTER COLUMN `SITEID` COMMENT 'Composite with WONUM.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.FAILUREREPORT') ALTER COLUMN `FAILURECODE` COMMENT 'FK to FAILURECODE.';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABOR') IS 'IBM Maximo labor master — one row per maintainable resource (employee or contractor). Joined by LABORCODE from LABTRANS, ASSIGNMENT, WORKORDER.LEAD. See the maximo-labor-resources skill for the full domain.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABOR') ALTER COLUMN `LABORCODE` COMMENT 'Business key — unique within ORGID.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABOR') ALTER COLUMN `ORGID` COMMENT 'Composite with LABORCODE.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABOR') ALTER COLUMN `PERSONID` COMMENT 'FK to PERSON. NULL for contractor resources that have no PERSON link.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABOR') ALTER COLUMN `CRAFT` COMMENT 'Default craft (FK to CRAFT).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABOR') ALTER COLUMN `SKILLLEVEL` COMMENT 'Default skill level.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABOR') ALTER COLUMN `STATUS` COMMENT 'ACTIVE or INACTIVE. Only ACTIVE can be assigned new work.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABOR') ALTER COLUMN `VENDOR` COMMENT 'FK to COMPANIES — populated for contractor labor (the contractor flag; there is no LABOR.OUTSIDELABOR column).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABOR') ALTER COLUMN `CALNUM` COMMENT 'Default calendar (FK to CALENDAR).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABOR') ALTER COLUMN `SHIFTNUM` COMMENT 'Default shift.';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.PERSON') IS 'Person master. PII-sensitive — handle names/emails/phone with care. See the maximo-labor-resources skill for usage patterns.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.PERSON') ALTER COLUMN `PERSONID` COMMENT 'Business key — unique globally (not org-scoped).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.PERSON') ALTER COLUMN `DISPLAYNAME` COMMENT 'Display name (PII).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.PERSON') ALTER COLUMN `STATUS` COMMENT 'ACTIVE or INACTIVE.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.PERSON') ALTER COLUMN `SUPERVISOR` COMMENT 'FK to PERSON.PERSONID — chain of supervision.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.PERSON') ALTER COLUMN `DEPARTMENT` COMMENT 'Department code.';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.CRAFT') IS 'Craft master (ELEC, MECH, INST, etc.).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.CRAFT') ALTER COLUMN `CRAFT` COMMENT 'Craft code.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.CRAFT') ALTER COLUMN `ORGID` COMMENT 'Composite.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.CRAFT') ALTER COLUMN `DESCRIPTION` COMMENT 'Free text.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.CRAFT') ALTER COLUMN `OUTSIDEONLY` COMMENT '1 if craft is contractor-only.';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABORCRAFTRATE') IS 'Pay rates per (labor, craft, skill level). Currency varies — do not aggregate RATE across CURRENCYCODE without normalizing.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABORCRAFTRATE') ALTER COLUMN `LABORCODE` COMMENT 'FK to LABOR.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABORCRAFTRATE') ALTER COLUMN `ORGID` COMMENT 'Composite.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABORCRAFTRATE') ALTER COLUMN `CRAFT` COMMENT 'FK to CRAFT.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABORCRAFTRATE') ALTER COLUMN `SKILLLEVEL` COMMENT 'Skill level granularity.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABORCRAFTRATE') ALTER COLUMN `RATE` COMMENT 'Pay rate.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LABORCRAFTRATE') ALTER COLUMN `CURRENCYCODE` COMMENT 'Currency — be careful aggregating across currencies.';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.QUALIFICATION') IS 'Qualification catalog. PERSONS hold qualifications via QUALPERSON. See the maximo-labor-resources skill.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.QUALIFICATION') ALTER COLUMN `QUALIFICATIONID` COMMENT 'Qualification code.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.QUALIFICATION') ALTER COLUMN `ORGID` COMMENT 'Composite.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.QUALIFICATION') ALTER COLUMN `DESCRIPTION` COMMENT 'Free text.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.QUALIFICATION') ALTER COLUMN `STATUS` COMMENT 'ACTIVE or INACTIVE.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.QUALIFICATION') ALTER COLUMN `CRAFT` COMMENT 'Optional — qualification tied to a craft.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.QUALIFICATION') ALTER COLUMN `REQUIREDFORWORK` COMMENT '1 if the qualification is mandatory for matched work.';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.QUALPERSON') IS 'Person ↔ Qualification with expiry. For ''qualified labor'' queries, filter STATUS=''ACTIVE'' AND (EXPIRYDATE IS NULL OR EXPIRYDATE > current_date()).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.QUALPERSON') ALTER COLUMN `PERSONID` COMMENT 'FK to PERSON.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.QUALPERSON') ALTER COLUMN `QUALIFICATIONID` COMMENT 'FK to QUALIFICATION.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.QUALPERSON') ALTER COLUMN `EFFECTIVEDATE` COMMENT 'When the person earned it.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.QUALPERSON') ALTER COLUMN `EXPIRYDATE` COMMENT 'When it lapses (NULL = never). Filter to keep current certs only.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.QUALPERSON') ALTER COLUMN `STATUS` COMMENT 'ACTIVE, EXPIRED, etc.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.QUALPERSON') ALTER COLUMN `CERTIFICATEID` COMMENT 'Optional cert identifier.';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.CERTIFICATION') IS 'Certification catalog (in some customer models, a subset of QUALIFICATION).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.CERTIFICATION') ALTER COLUMN `CERTIFICATIONID` COMMENT 'Certification code.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.CERTIFICATION') ALTER COLUMN `DESCRIPTION` COMMENT 'Free text.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.CERTIFICATION') ALTER COLUMN `STATUS` COMMENT 'ACTIVE or INACTIVE.';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.AMCREW') IS 'Crew master. Crews are time-bound groupings of labor — see AMCREWLABOR for membership. Keyed on (ORGID, AMCREW).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.AMCREW') ALTER COLUMN `AMCREW` COMMENT 'Crew identifier (business key, unique within ORGID).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.AMCREW') ALTER COLUMN `ORGID` COMMENT 'Composite.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.AMCREW') ALTER COLUMN `CREWTYPE` COMMENT 'FK to the crew-type master AMCREWT (required craft mix).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.AMCREW') ALTER COLUMN `STATUS` COMMENT 'ACTIVE or INACTIVE.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.AMCREW') ALTER COLUMN `BASELOCATION` COMMENT 'Home location.';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.AMCREWLABOR') IS 'Crew composition. Time-bounded — EFFECTIVEDATE/ENDDATE define membership window. For current crew, filter EFFECTIVEDATE <= current_date() AND (ENDDATE IS NULL OR ENDDATE > current_date()). Keyed on AMCREW.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.AMCREWLABOR') ALTER COLUMN `AMCREW` COMMENT 'FK to AMCREW.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.AMCREWLABOR') ALTER COLUMN `ORGID` COMMENT 'Composite.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.AMCREWLABOR') ALTER COLUMN `LABORCODE` COMMENT 'FK to LABOR — one row per labor member.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.AMCREWLABOR') ALTER COLUMN `EFFECTIVEDATE` COMMENT 'Membership start.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.AMCREWLABOR') ALTER COLUMN `ENDDATE` COMMENT 'Membership end (NULL = current).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.AMCREWLABOR') ALTER COLUMN `POSITION` COMMENT 'Crew position (lead, member, etc.).';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.PERSONGROUP') IS 'Named person group. Members in PERSONGROUPTEAM. Used by workflow assignment, paging, on-call rotation. Can nest — beware loops.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.PERSONGROUP') ALTER COLUMN `PERSONGROUP` COMMENT 'Group identifier.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.PERSONGROUP') ALTER COLUMN `DESCRIPTION` COMMENT 'Free text.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.PERSONGROUP') ALTER COLUMN `USEFORAVAIL` COMMENT '1 if usable for availability/on-call logic.';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.CALENDAR') IS 'Working calendar identifier. Specific work periods (shifts, days off) in WORKPERIOD.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.CALENDAR') ALTER COLUMN `CALNUM` COMMENT 'Calendar identifier.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.CALENDAR') ALTER COLUMN `ORGID` COMMENT 'Composite.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.CALENDAR') ALTER COLUMN `DESCRIPTION` COMMENT 'Free text.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.CALENDAR') ALTER COLUMN `STARTDATE` COMMENT 'Calendar validity start.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.CALENDAR') ALTER COLUMN `ENDDATE` COMMENT 'Calendar validity end.';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WORKPERIOD') IS 'Specific work periods per calendar — one row per shift per work date. Often sparsely populated — probe coverage (MIN/MAX shiftstart) before claiming ''we have capacity for X''.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WORKPERIOD') ALTER COLUMN `CALNUM` COMMENT 'FK to CALENDAR.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WORKPERIOD') ALTER COLUMN `SITEID` COMMENT 'Composite.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WORKPERIOD') ALTER COLUMN `SHIFTNUM` COMMENT 'Shift identifier.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WORKPERIOD') ALTER COLUMN `WORKDATE` COMMENT 'The calendar date this work period falls on.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WORKPERIOD') ALTER COLUMN `SHIFTSTART` COMMENT 'Shift start (date+time).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.WORKPERIOD') ALTER COLUMN `SHIFTEND` COMMENT 'Shift end (date+time).';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSIGNMENT') IS 'Labor ↔ WO assignment. One row per labor scheduled for specific WO work.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSIGNMENT') ALTER COLUMN `WONUM` COMMENT 'FK to WORKORDER.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSIGNMENT') ALTER COLUMN `SITEID` COMMENT 'Composite.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSIGNMENT') ALTER COLUMN `LABORCODE` COMMENT 'FK to LABOR (NULL if assigned to a CRAFT only, not a specific person).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSIGNMENT') ALTER COLUMN `CRAFT` COMMENT 'Craft assigned.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSIGNMENT') ALTER COLUMN `SCHEDDATE` COMMENT 'Scheduled start.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSIGNMENT') ALTER COLUMN `ESTDUR` COMMENT 'Estimated duration.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSIGNMENT') ALTER COLUMN `STATUS` COMMENT 'NEW, ASSIGNED, COMPLETE.';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LOCHIERARCHY') IS 'Multi-system parent-child for LOCATIONS. One row per (location, parent, systemid). A single location can appear in multiple hierarchies (Operating, Storeroom, Network). Always filter SYSTEMID. See the maximo-asset-hierarchy skill.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LOCHIERARCHY') ALTER COLUMN `LOCATION` COMMENT 'The child location.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LOCHIERARCHY') ALTER COLUMN `PARENT` COMMENT 'The parent location.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LOCHIERARCHY') ALTER COLUMN `SYSTEMID` COMMENT 'Hierarchy system — typically PRIMARY.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LOCHIERARCHY') ALTER COLUMN `SITEID` COMMENT 'Composite.';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LOCANCESTOR') IS 'Location closure table — one row per (descendant, ancestor) pair at any depth. The IBM-canonical traversal mechanism for hierarchical rollups. Use instead of naïve PARENT self-joins for multi-level analytics.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LOCANCESTOR') ALTER COLUMN `LOCATION` COMMENT 'The descendant location.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LOCANCESTOR') ALTER COLUMN `ANCESTOR` COMMENT 'An ancestor at any depth.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LOCANCESTOR') ALTER COLUMN `SYSTEMID` COMMENT 'Hierarchy system — match LOCHIERARCHY.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.LOCANCESTOR') ALTER COLUMN `SITEID` COMMENT 'Composite.';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSETANCESTOR') IS 'Asset closure table — one row per (descendant, ancestor) pair at any depth in the ASSET hierarchy.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSETANCESTOR') ALTER COLUMN `ASSETNUM` COMMENT 'The descendant asset.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSETANCESTOR') ALTER COLUMN `ANCESTOR` COMMENT 'An ancestor asset at any depth.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSETANCESTOR') ALTER COLUMN `SITEID` COMMENT 'Composite.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSETANCESTOR') ALTER COLUMN `HIERARCHYLEVELS` COMMENT 'Number of levels between descendant and ancestor (0 = self if convention includes it).';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.SYSTEM') IS 'Hierarchy system definition. Each LOCHIERARCHY row belongs to one system. Default is PRIMARY (the operational hierarchy).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.SYSTEM') ALTER COLUMN `SYSTEMID` COMMENT 'System identifier.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.SYSTEM') ALTER COLUMN `ORGID` COMMENT 'Org-scoped.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.SYSTEM') ALTER COLUMN `DESCRIPTION` COMMENT 'Free text.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.SYSTEM') ALTER COLUMN `NETWORK` COMMENT '1 if network-type (graph rather than tree).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.SYSTEM') ALTER COLUMN `PRIMARYSYSTEM` COMMENT '1 if this is the default system.';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.CLASSSTRUCTURE') IS 'Asset / location classification tree. A taxonomy hierarchy applied via CLASSSTRUCTUREID. Separate from LOCATIONS physical hierarchy — these answer different questions. Maximo does not ship a CLASSANCESTOR closure table — use recursive CTE on PARENT.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.CLASSSTRUCTURE') ALTER COLUMN `CLASSSTRUCTUREID` COMMENT 'Class identifier.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.CLASSSTRUCTURE') ALTER COLUMN `PARENT` COMMENT 'Parent class.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.CLASSSTRUCTURE') ALTER COLUMN `DESCRIPTION` COMMENT 'E.g. ''Centrifugal Pump'', ''Rotating Equipment''.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.CLASSSTRUCTURE') ALTER COLUMN `CLASSIFICATIONID` COMMENT 'Full classification path string in some installs.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.CLASSSTRUCTURE') ALTER COLUMN `USEWITH` COMMENT 'Whether this class applies to ASSET, LOCATIONS, ITEM, etc.';

COMMENT ON TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSETSPEC') IS 'Per-asset specification values, driven by CLASSSPEC at the class level. For analytics like ''show me all pumps with flow rate > 5000 gpm'', join ASSETSPEC on ASSETATTRID.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSETSPEC') ALTER COLUMN `ASSETNUM` COMMENT 'FK to ASSET.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSETSPEC') ALTER COLUMN `SITEID` COMMENT 'Composite.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSETSPEC') ALTER COLUMN `ASSETATTRID` COMMENT 'Specification attribute identifier (e.g. FLOWRATE).';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSETSPEC') ALTER COLUMN `ALNVALUE` COMMENT 'Alphanumeric value.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSETSPEC') ALTER COLUMN `NUMVALUE` COMMENT 'Numeric value.';

ALTER TABLE IDENTIFIER(:catalog || '.' || :silver_schema || '.ASSETSPEC') ALTER COLUMN `DATEVALUE` COMMENT 'Date value.';

