"""Apply standardized Unity Catalog table and column comments to Maximo Silver tables.

Reads a JSON file describing the canonical Maximo MBO descriptions and either
(a) emits a runnable SQL file for SQL Editor / Pro-warehouse execution
(--emit-sql), or (b) writes directly to UC via the Databricks SDK (--apply).

SAFETY: PREVIEW (no writes) is the default. UC is modified ONLY when --apply is
passed, which must never be used without the customer's explicit approval of
the previewed statements (per the multi-checkpoint vetting flow in SKILL.md).

Usage:
    # 1) PREVIEW (default — safe, no writes). Prints the statements + (optionally)
    #    writes them to a runnable .sql file for SQL Editor execution:
    python apply_uc_comments.py --catalog eam --schema maximo_silver \
        --comments-file maximo_comments.json \
        --emit-sql apply_uc_comments.sql

    # 2) ONLY after explicit user approval at Checkpoint 2 of the vetted flow,
    #    apply via Python SDK:
    python apply_uc_comments.py --catalog eam --schema maximo_silver \
        --comments-file maximo_comments.json --apply --warehouse-id <id>

    # 3) Scope by module activity (default: active). With a profile file,
    #    DORMANT modules are excluded by default; pass --scope all to include them:
    python apply_uc_comments.py --catalog eam --schema maximo_silver \
        --comments-file maximo_comments.json \
        --profile-path /Workspace/Users/.../draft_profile.json \
        --scope active|all \
        --emit-sql apply_uc_comments.sql

The comments file shape (see maximo_comments.json):
    { "WORKORDER": { "table_comment": "...",
                     "columns": { "WONUM": "...", ... } },
      ... }

The SQL artifact uses Databricks parameter markers (`:catalog`, `:silver_schema`)
via IDENTIFIER() for the namespace, so the customer binds them in SQL Editor at
execution time. The committed apply_uc_comments.sql is generated by running this
script with --emit-sql; CI verifies the committed copy matches.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Standard Maximo table → module map.
# Mirrors the mapping used by introspect_schema.py for activity verdicts.
# Tables not listed here are treated as belonging to no specific module and
# always included in scope (e.g. SYNONYMDOMAIN, MAXVARS).
TABLE_MODULE_MAP = {
    # Work Management
    "WORKORDER": "work_management",
    "WOSTATUS": "work_management",
    "LABTRANS": "work_management",
    "WPLABOR": "work_management",
    "WPMATERIAL": "work_management",
    "JOBPLAN": "work_management",
    "JPLABOR": "work_management",
    "JPMATERIAL": "work_management",
    # PM
    "PM": "preventive_maintenance",
    "PMSEQUENCE": "preventive_maintenance",
    # Asset Management
    "ASSET": "asset_management",
    "ASSETMETER": "asset_integrity",
    "METERREADING": "asset_integrity",
    "LOCATIONS": "asset_management",
    "LOCHIERARCHY": "asset_hierarchy",
    "LOCANCESTOR": "asset_hierarchy",
    "ASSETANCESTOR": "asset_hierarchy",
    "CLASSSTRUCTURE": "asset_hierarchy",
    # Reliability / Failure
    "FAILUREREPORT": "reliability",
    "FAILURECODE": "reliability",
    # Inventory / Purchasing
    "INVENTORY": "inventory",
    "INVBALANCES": "inventory",
    "INVUSE": "inventory",
    "ITEM": "inventory",
    "PO": "procurement",
    "POLINE": "procurement",
    "PR": "procurement",
    "INVOICE": "procurement",
    "INVOICELINE": "procurement",
    "COMPANIES": "procurement",
    # Service Desk
    "TICKET": "service_desk",
    "SR": "service_desk",
    "INCIDENT": "service_desk",
    "PROBLEM": "service_desk",
    # Labor
    "LABOR": "labor_resources",
    "PERSON": "labor_resources",
    "PERSONGROUP": "labor_resources",
    "CRAFT": "labor_resources",
    "LABORCRAFTRATE": "labor_resources",
    "QUALIFICATION": "labor_resources",
    "CERTIFICATION": "labor_resources",
    "QUALPERSON": "labor_resources",
    "CREW": "labor_resources",
    "CREWLABOR": "labor_resources",
    "CALENDAR": "labor_resources",
    "WORKPERIOD": "labor_resources",
    "ASSIGNMENT": "labor_resources",
    # Workflow & Approvals
    "WFINSTANCE": "workflow_and_approvals",
    "WFASSIGNMENT": "workflow_and_approvals",
    "WFPROCESS": "workflow_and_approvals",
    # HSE (PLUSG)
    "PLUSGPERMITWORK": "hse",
    "PLUSGINCPERSON": "hse",
    "PLUSGRELATEDREC": "hse",
}


def sql_literal(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def build_statements_python(catalog: str, schema: str, comments: dict) -> list[str]:
    """Build statements for direct SDK execution — hardcoded catalog.schema.table."""
    statements: list[str] = []
    for table_name, spec in comments.items():
        fq = f"`{catalog}`.`{schema}`.`{table_name}`"
        if "table_comment" in spec:
            statements.append(f"COMMENT ON TABLE {fq} IS {sql_literal(spec['table_comment'])}")
        for col, col_comment in spec.get("columns", {}).items():
            statements.append(
                f"ALTER TABLE {fq} ALTER COLUMN `{col}` COMMENT {sql_literal(col_comment)}"
            )
    return statements


def build_statements_sql_artifact(comments: dict) -> list[str]:
    """Build statements for the SQL artifact — uses :catalog.:silver_schema parameters
    via IDENTIFIER() for the namespace, so SQL Editor users can bind at execution.

    The format the customer sees in apply_uc_comments.sql:

        COMMENT ON TABLE
          IDENTIFIER(:catalog || '.' || :silver_schema || '.WORKORDER')
          IS 'description';
    """
    statements: list[str] = []
    for table_name, spec in comments.items():
        fq_identifier = f"IDENTIFIER(:catalog || '.' || :silver_schema || '.{table_name}')"
        if "table_comment" in spec:
            statements.append(
                f"COMMENT ON TABLE {fq_identifier} IS {sql_literal(spec['table_comment'])}"
            )
        for col, col_comment in spec.get("columns", {}).items():
            statements.append(
                f"ALTER TABLE {fq_identifier} "
                f"ALTER COLUMN `{col}` COMMENT {sql_literal(col_comment)}"
            )
    return statements


def filter_by_scope(comments: dict, scope: str, profile_path: Path | None) -> dict:
    """Filter the comments dict by module activity scope.

    scope='all'    → no filtering; return all tables in comments
    scope='active' → require a profile_path; keep only tables whose module is
                     ACTIVE or INSUFFICIENT_DATA, drop DORMANT and NOT_INGESTED.
                     Tables not in TABLE_MODULE_MAP are always kept.
    """
    if scope == "all":
        return comments

    if profile_path is None or not profile_path.exists():
        # No profile to scope from; treat as scope=all but warn.
        print(
            "WARNING: --scope active requested but no --profile-path provided "
            "(or file missing). Treating as --scope all.",
            file=sys.stderr,
        )
        return comments

    profile = json.loads(profile_path.read_text())
    module_activity = profile.get("module_activity", {})
    active_modules = {
        m for m, info in module_activity.items()
        if info.get("verdict") in ("ACTIVE", "INSUFFICIENT_DATA")
    }

    filtered: dict = {}
    skipped: list[str] = []
    for table_name, spec in comments.items():
        module = TABLE_MODULE_MAP.get(table_name)
        if module is None:
            # Tables not in the module map (e.g. SYNONYMDOMAIN, MAXVARS) — always include
            filtered[table_name] = spec
        elif module in active_modules:
            filtered[table_name] = spec
        else:
            skipped.append(f"{table_name} (module={module})")

    if skipped:
        print(
            f"# scope=active: skipped {len(skipped)} tables in DORMANT/NOT_INGESTED modules. "
            f"Pass --scope all to include them.",
            file=sys.stderr,
        )
        for s in skipped[:10]:
            print(f"#   {s}", file=sys.stderr)
        if len(skipped) > 10:
            print(f"#   …and {len(skipped) - 10} more", file=sys.stderr)
    return filtered


SQL_ARTIFACT_HEADER = """\
-- =============================================================================
-- Maximo UC table + column comments
-- =============================================================================
-- Generated from scripts/maximo_comments.json. To regenerate, run:
--
--   python scripts/apply_uc_comments.py \\
--     --comments-file scripts/maximo_comments.json \\
--     --emit-sql scripts/apply_uc_comments.sql
--
-- HOW TO RUN:
--   1. Open this file in Databricks SQL Editor against the customer's warehouse.
--   2. Bind parameters: :catalog (e.g. eam) and :silver_schema (e.g. maximo_silver).
--   3. Review every statement with the customer.
--   4. Execute ONLY after explicit, unambiguous customer approval (per the
--      multi-checkpoint vetting flow in maximo-setup/SKILL.md §Optional).
--
-- This file modifies customer-owned Unity Catalog objects (table + column
-- comments). It must never run without explicit user approval.
-- =============================================================================

"""


def emit_sql_artifact(path: Path, statements: list[str]) -> None:
    """Write a runnable SQL artifact for SQL Editor execution."""
    with path.open("w") as f:
        f.write(SQL_ARTIFACT_HEADER)
        for s in statements:
            f.write(f"{s};\n\n")


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Preview (default) or apply UC comments on Maximo Silver tables. "
            "PREVIEW writes nothing. --apply executes via SDK; --emit-sql writes "
            "a runnable .sql file for SQL Editor execution. UC writes ONLY after "
            "explicit customer approval (see SKILL.md §Optional)."
        )
    )
    parser.add_argument("--catalog", help="UC catalog. Required with --apply.")
    parser.add_argument("--schema", help="Silver schema. Required with --apply.")
    parser.add_argument("--comments-file", required=True, type=Path)
    parser.add_argument(
        "--emit-sql",
        type=Path,
        help=(
            "Write the COMMENT/ALTER statements to a runnable SQL file (uses "
            ":catalog and :silver_schema parameter markers via IDENTIFIER()). "
            "Customer reviews + executes in SQL Editor themselves."
        ),
    )
    parser.add_argument(
        "--scope",
        choices=("active", "all"),
        default="active",
        help=(
            "Module activity scope. 'active' (default) requires --profile-path "
            "and drops tables in DORMANT/NOT_INGESTED modules. 'all' includes "
            "every table in the comments file."
        ),
    )
    parser.add_argument(
        "--profile-path",
        type=Path,
        help=(
            "Path to draft_profile.json (from introspect_schema.py) for "
            "--scope active to read module_activity. Optional with --scope all."
        ),
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help=(
            "Write the comments to Unity Catalog via the Databricks SDK. Use "
            "ONLY after explicit customer approval of the previewed statements "
            "(Checkpoint 2 in SKILL.md §Optional)."
        ),
    )
    parser.add_argument(
        "--warehouse-id",
        help="SQL warehouse ID for --apply. Required with --apply.",
    )
    args = parser.parse_args()

    comments = json.loads(args.comments_file.read_text())
    print(f"loaded {len(comments)} tables from {args.comments_file}")

    # Apply scope filtering (requires profile for scope=active; otherwise no-op)
    comments = filter_by_scope(comments, args.scope, args.profile_path)
    print(f"after --scope {args.scope}: {len(comments)} tables in scope\n")

    # Build preview statements (the SQL-artifact form — what the customer sees)
    artifact_statements = build_statements_sql_artifact(comments)
    print(
        f"PREVIEW: {len(artifact_statements)} statements would run. "
        f"Review with the customer before any execution.\n"
    )
    for s in artifact_statements:
        print(f"{s};\n")

    # Optional: write the runnable SQL artifact
    if args.emit_sql is not None:
        emit_sql_artifact(args.emit_sql, artifact_statements)
        print(f"\nWrote runnable SQL artifact: {args.emit_sql}", file=sys.stderr)
        print(
            "  Open in SQL Editor, bind :catalog and :silver_schema, review, then execute.",
            file=sys.stderr,
        )

    # If --apply, execute via SDK (with hardcoded catalog.schema; no parameters at runtime)
    if not args.apply:
        if not args.emit_sql:
            print(
                "\nPREVIEW ONLY — no changes written. Re-run with --emit-sql to "
                "produce a runnable SQL artifact, or --apply --warehouse-id <id> "
                "ONLY after explicit customer approval.",
                file=sys.stderr,
            )
        return 0

    if not args.catalog or not args.schema:
        print("--catalog and --schema are required with --apply", file=sys.stderr)
        return 2
    if not args.warehouse_id:
        print("--warehouse-id is required with --apply", file=sys.stderr)
        return 2

    # Build hardcoded-namespace statements for SDK execution
    apply_statements = build_statements_python(args.catalog, args.schema, comments)

    from databricks.sdk import WorkspaceClient  # type: ignore

    client = WorkspaceClient()
    for s in apply_statements:
        client.statement_execution.execute_statement(
            warehouse_id=args.warehouse_id, statement=s, wait_timeout="30s"
        )
    print(
        f"\nApplied {len(apply_statements)} statements to "
        f"{args.catalog}.{args.schema}",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
