"""Generate a workspace-tier glossary skill from an interview answers JSON file.

Usage:
    python generate_glossary.py \
        --customer northstar \
        --answers answers.json \
        --output /Workspace/.assistant/skills/northstar-maximo-glossary/SKILL.md

The answers.json shape is documented in interview.md.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import date
from pathlib import Path


SKILL_TEMPLATE = """---
name: {customer}-maximo-glossary
description: |
  Customer-specific business-jargon to Maximo schema mappings for {customer_proper}.
  Use whenever a Maximo-related question uses {customer_proper} business terms
  (sites, regions, asset classes, custom fields, etc.). Compose with the
  maximo-* enterprise skills.
tags:
  - data-source:ibm-maximo
  - tier:workspace
  - customer:{customer}
---

# {customer_proper} — Maximo Business Glossary

Generated by `maximo-setup` on {generated_at}. Edit when business terms or schema mappings change.

{sections}

## How to use

When you encounter a {customer_proper} business term:
1. Check this glossary first.
2. If the term is here, use the mapping.
3. If not, ASK the user before guessing.
4. If you learn a new mapping during the session, suggest adding it via a re-run of `maximo-setup`.
"""


def _md_table(headers: list[str], rows: list[list[str]]) -> str:
    if not rows:
        return "_(none captured)_"
    lines = ["| " + " | ".join(headers) + " |"]
    lines.append("|" + "|".join("---" for _ in headers) + "|")
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines)


def _section_sites(sites: dict) -> str:
    rows = [
        [f"`{name}`", ", ".join(f"`'{v}'`" for v in ids)]
        for name, ids in sites.items()
    ]
    return "## Sites\n\n" + _md_table(["Business term", "SITEID values"], rows)


def _section_hierarchy(hierarchy: dict) -> str:
    body = "## Asset / location hierarchy\n\n"
    if not hierarchy:
        return body + "_(none captured)_"
    for name, mapping in hierarchy.items():
        body += f"- **{name}** → {mapping}\n"
    return body.rstrip()


def _section_asset_classes(classes: dict) -> str:
    rows = [
        [f"`{name}`", ", ".join(f"`{v}`" for v in ids)]
        for name, ids in classes.items()
    ]
    return "## Asset classes\n\n" + _md_table(["Business term", "CLASSSTRUCTUREID values"], rows)


def _section_criticality(crit: dict) -> str:
    body = "## Criticality conventions\n\n"
    if not crit:
        return body + "_(none captured)_"
    for level, rule in crit.items():
        body += f"- **{level}** → `{rule}`\n"
    return body.rstrip()


def _section_open_statuses(statuses: list[str]) -> str:
    if not statuses:
        return "## Status conventions\n\n_(not captured)_"
    formatted = ", ".join(f"'{s}'" for s in statuses)
    return f"""## Status conventions

The customer's definition of "open" work orders:

```sql
WORKORDER.STATUS IN ({formatted})
```"""


def _section_worktypes(worktypes: dict) -> str:
    rows = [
        [cat, ", ".join(f"`{v}`" for v in values)]
        for cat, values in worktypes.items()
    ]
    return "## Work-type codes\n\n" + _md_table(["Business category", "WORKTYPE values"], rows)


def _section_custom_columns(cols: dict) -> str:
    rows = [[f"`{col}`", desc] for col, desc in cols.items()]
    return "## Custom columns\n\n" + _md_table(["Column", "Meaning"], rows)


def _section_custom_tables(tables: dict) -> str:
    rows = [[f"`{table}`", desc] for table, desc in tables.items()]
    return "## Custom tables\n\n" + _md_table(["Table", "Join + meaning"], rows)


def _section_regulatory(codes: list[str]) -> str:
    return "## Regulatory codes used\n\n" + (", ".join(codes) if codes else "_(none captured)_")


def _section_tribal(facts: list[str]) -> str:
    body = "## Tribal knowledge\n\n"
    if not facts:
        return body + "_(none captured)_"
    return body + "\n".join(f"- {f}" for f in facts)


SECTIONS = [
    ("sites", _section_sites, {}),
    ("location_hierarchy", _section_hierarchy, {}),
    ("asset_classes", _section_asset_classes, {}),
    ("criticality", _section_criticality, {}),
    ("open_statuses", _section_open_statuses, []),
    ("worktypes", _section_worktypes, {}),
    ("custom_columns", _section_custom_columns, {}),
    ("custom_tables", _section_custom_tables, {}),
    ("regulatory_codes", _section_regulatory, []),
    ("tribal_knowledge", _section_tribal, []),
]


def render(answers: dict) -> str:
    customer = answers["customer"]
    sections = "\n\n".join(
        renderer(answers.get(key, default))
        for key, renderer, default in SECTIONS
    )
    return SKILL_TEMPLATE.format(
        customer=customer,
        customer_proper=customer.replace("-", " ").title(),
        generated_at=date.today().isoformat(),
        sections=sections,
    )


def main():
    parser = argparse.ArgumentParser(description="Generate a Maximo workspace glossary skill.")
    parser.add_argument("--customer", required=True, help="Short kebab-case customer name (e.g. northstar).")
    parser.add_argument("--answers", required=True, type=Path, help="Path to answers.json (see interview.md).")
    parser.add_argument("--output", required=True, type=Path, help="Output SKILL.md path.")
    args = parser.parse_args()

    answers = json.loads(args.answers.read_text())
    if answers.get("customer") != args.customer:
        # Allow CLI customer to override the answer file's value.
        answers["customer"] = args.customer

    rendered = render(answers)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered)
    print(f"wrote {args.output} ({len(rendered):,} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
