"""Generate a workspace-tier glossary skill from an interview answers JSON file.

Usage:
    python generate_glossary.py \
        --customer northstar \
        --answers answers.json \
        --output /Workspace/.assistant/skills/maximo/northstar-maximo-glossary/SKILL.md
        # Write into the maximo/ group folder so the glossary sits beside the family
        # (use /Users/<email>/.assistant/skills/maximo/... for a user-scoped install).

The answers.json shape is documented in interview.md.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import date
from pathlib import Path


SKILL_TEMPLATE = """---
name: {customer}-maximo-glossary
description: |
  {customer_proper}'s Maximo business glossary — maps {customer_proper} terms
  ({term_hints}) to Maximo schema (SITEIDs, CLASSSTRUCTUREIDs, status/worktype
  codes, custom columns) and records their industry and how they use Maximo. Use
  for ANY Maximo question that uses {customer_proper} business vocabulary. Composes
  with the maximo-* skills.
metadata:
  version: "0.1.0"
parent: maximo-overview
---

# {customer_proper} — Maximo Business Glossary

Generated by `maximo-setup` on {generated_at}. Edit when business terms or schema mappings change.

{sections}

## How to use

When you encounter a {customer_proper} business term:
1. Check this glossary first.
2. If the term is here, use the mapping.
3. If not, ASK the user before guessing.
4. If you learn a new mapping during the session, suggest adding it via a re-run of `maximo-setup`.
"""


def _md_table(headers: list[str], rows: list[list[str]]) -> str:
    if not rows:
        return "_(none captured)_"
    lines = ["| " + " | ".join(headers) + " |"]
    lines.append("|" + "|".join("---" for _ in headers) + "|")
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines)


def _section_sites(sites: dict) -> str:
    rows = [
        [f"`{name}`", ", ".join(f"`'{v}'`" for v in ids)]
        for name, ids in sites.items()
    ]
    return "## Sites\n\n" + _md_table(["Business term", "SITEID values"], rows)


def _section_hierarchy(hierarchy: dict) -> str:
    body = "## Asset / location hierarchy\n\n"
    if not hierarchy:
        return body + "_(none captured)_"
    for name, mapping in hierarchy.items():
        body += f"- **{name}** → {mapping}\n"
    return body.rstrip()


def _section_asset_classes(classes: dict) -> str:
    rows = [
        [f"`{name}`", ", ".join(f"`{v}`" for v in ids)]
        for name, ids in classes.items()
    ]
    return "## Asset classes\n\n" + _md_table(["Business term", "CLASSSTRUCTUREID values"], rows)


def _section_criticality(crit: dict) -> str:
    body = "## Criticality conventions\n\n"
    if not crit:
        return body + "_(none captured)_"
    for level, rule in crit.items():
        body += f"- **{level}** → `{rule}`\n"
    return body.rstrip()


def _section_open_statuses(statuses: list[str]) -> str:
    if not statuses:
        return "## Status conventions\n\n_(not captured)_"
    formatted = ", ".join(f"'{s}'" for s in statuses)
    return f"""## Status conventions

The customer's definition of "open" work orders:

```sql
WORKORDER.STATUS IN ({formatted})
```"""


def _section_worktypes(worktypes: dict) -> str:
    rows = [
        [cat, ", ".join(f"`{v}`" for v in values)]
        for cat, values in worktypes.items()
    ]
    return "## Work-type codes\n\n" + _md_table(["Business category", "WORKTYPE values"], rows)


def _section_custom_columns(cols: dict) -> str:
    rows = [[f"`{col}`", desc] for col, desc in cols.items()]
    return "## Custom columns\n\n" + _md_table(["Column", "Meaning"], rows)


def _section_custom_tables(tables: dict) -> str:
    rows = [[f"`{table}`", desc] for table, desc in tables.items()]
    return "## Custom tables\n\n" + _md_table(["Table", "Join + meaning"], rows)


def _section_regulatory(codes: list[str]) -> str:
    return "## Regulatory codes used\n\n" + (", ".join(codes) if codes else "_(none captured)_")


def _section_tribal(facts: list[str]) -> str:
    body = "## Tribal knowledge\n\n"
    if not facts:
        return body + "_(none captured)_"
    return body + "\n".join(f"- {f}" for f in facts)


def _section_industry_usage(iu: dict) -> str:
    body = "## Industry & Maximo usage\n\n"
    if not iu:
        return body + "_(not captured)_"
    lines = []
    if iu.get("industry"):
        lines.append(f"- **Industry:** {iu['industry']}")
    if iu.get("industry_solutions"):
        lines.append(f"- **Industry solutions:** {', '.join(iu['industry_solutions'])}")
    if iu.get("modules_in_use"):
        lines.append(f"- **Modules used in Maximo:** {', '.join(iu['modules_in_use'])}")
    if iu.get("modules_elsewhere"):
        lines.append("- **Handled outside Maximo:** "
                     + ", ".join(f"{k} ({v})" for k, v in iu["modules_elsewhere"].items()))
    if iu.get("maintenance_maturity"):
        lines.append(f"- **Maintenance maturity:** {iu['maintenance_maturity']}")
    if iu.get("kpis"):
        lines.append("- **KPIs tracked:** " + "; ".join(iu["kpis"]))
    for note in iu.get("notes", []):
        lines.append(f"- {note}")
    body += "\n".join(lines)
    body += ("\n\n> Scope answers to this: skip the O&G-only skills (`maximo-integrity`, "
             "`maximo-hse`) when the industry isn't O&G / no `plusg*` tables.")
    return body


def _term_hints(answers: dict) -> str:
    """A few real site / asset-class names injected into the description for discovery."""
    hints = list(answers.get("sites", {}))[:3] + list(answers.get("asset_classes", {}))[:3]
    return ", ".join(hints) if hints else "sites, regions, asset classes, custom fields"


SECTIONS = [
    ("industry_usage", _section_industry_usage, {}),
    ("sites", _section_sites, {}),
    ("location_hierarchy", _section_hierarchy, {}),
    ("asset_classes", _section_asset_classes, {}),
    ("criticality", _section_criticality, {}),
    ("open_statuses", _section_open_statuses, []),
    ("worktypes", _section_worktypes, {}),
    ("custom_columns", _section_custom_columns, {}),
    ("custom_tables", _section_custom_tables, {}),
    ("regulatory_codes", _section_regulatory, []),
    ("tribal_knowledge", _section_tribal, []),
]


def render(answers: dict) -> str:
    customer = answers["customer"]
    sections = "\n\n".join(
        renderer(answers.get(key, default))
        for key, renderer, default in SECTIONS
    )
    return SKILL_TEMPLATE.format(
        customer=customer,
        customer_proper=customer.replace("-", " ").title(),
        term_hints=_term_hints(answers),
        generated_at=date.today().isoformat(),
        sections=sections,
    )


def main():
    parser = argparse.ArgumentParser(description="Generate a Maximo workspace glossary skill.")
    parser.add_argument("--customer", required=True, help="Short kebab-case customer name (e.g. northstar).")
    parser.add_argument("--answers", required=True, type=Path, help="Path to answers.json (see interview.md).")
    parser.add_argument("--output", required=True, type=Path, help="Output SKILL.md path.")
    args = parser.parse_args()

    answers = json.loads(args.answers.read_text())
    if answers.get("customer") != args.customer:
        # Allow CLI customer to override the answer file's value.
        answers["customer"] = args.customer

    rendered = render(answers)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered)
    print(f"wrote {args.output} ({len(rendered):,} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
