#!/usr/bin/env python3
"""
generate_glossary.py — write the <customer>-wellview-glossary workspace skill.

Consumes the interview answers (answers.json) and renders the glossary SKILL.md from
glossary_template.md's structure. The glossary is the canonical -> physical bridge every
analytical WellView skill defers to: spine table mapping, the MASTER UNIT of every numeric
column, LV code decodes, calc-vs-stored notes, and business jargon.

Usage:
  python generate_glossary.py --customer northstar --answers answers.json \
      --output /Workspace/.assistant/skills/northstar-wellview-glossary/SKILL.md

answers.json shape (abbreviated):
  {
    "customer_name": "Northstar Energy",
    "date": "2026-06-04",
    "catalog_schema": "wellview.silver",
    "spine": [{"canonical": "...", "table": "...", "grain": "...", "parent": "..."}],
    "units": [{"column": "...", "table": "...", "unit": "...", "notes": "..."}],
    "lv_decodes": [{"column": "...", "lv_table": "...", "map": "...", "npt": "..."}],
    "calc_stored": [{"metric": "...", "stored": "...", "recompute": "..."}],
    "jargon": ["...", "..."],
    "domains": "drilling, completion, workover"
  }
"""
import argparse
import json
import os


def _rows(items, cols, get):
    out = []
    for it in items:
        out.append("| " + " | ".join(get(it, c) for c in cols) + " |")
    return "\n".join(out) if out else "| _unknown — fill in interview_ |"


def render(a: dict) -> str:
    name = f"{a['customer_short']}-wellview-glossary"
    g = lambda it, k: str(it.get(k, "_unknown_"))
    return f"""---
name: {name}
description: |
  Customer-specific physical-schema and business-jargon mappings for {a['customer_name']}'s
  Peloton WellView data. Use whenever a WellView question uses {a['customer_name']} terms,
  table/column names, well/rig names, or codes. Records the master UNIT of every numeric
  column and decodes the LV code tables. Compose with the wellview-* skills.
metadata:
  version: "0.1.0"
parent: wellview-overview
---

# {a['customer_name']} — WellView Glossary

Generated by `wellview-setup` on {a.get('date', '<date>')}. Edit when schema, codes, or units change.

## Catalog / schema
- WellView Silver: `{a['catalog_schema']}`

## Spine tables (canonical -> physical)
| Canonical | Physical table | Grain | Parent edge |
|---|---|---|---|
{_rows(a.get('spine', []), ['canonical','table','grain','parent'], g)}

## Master units (THE critical section)
| Column | Table | Master unit | Notes |
|---|---|---|---|
{_rows(a.get('units', []), ['column','table','unit','notes'], g)}

## LV code decodes
| Coded column | LV table | Code->label | NPT class? |
|---|---|---|---|
{_rows(a.get('lv_decodes', []), ['column','lv_table','map','npt'], g)}

## Calc-vs-stored
| Metric | Stored column? | If not, recompute via |
|---|---|---|
{_rows(a.get('calc_stored', []), ['metric','stored','recompute'], g)}

## Business jargon
{chr(10).join('- ' + j for j in a.get('jargon', ['_unknown — fill in interview_']))}

## Domains present in this install
- {a.get('domains', '_unknown — confirm from schema inventory_')}
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--customer", required=True, help="short name for filenames")
    ap.add_argument("--answers", required=True)
    ap.add_argument("--output", required=True)
    args = ap.parse_args()

    with open(args.answers) as f:
        a = json.load(f)
    a.setdefault("customer_short", args.customer)
    a.setdefault("customer_name", args.customer.replace("-", " ").title())

    content = render(a)
    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, "w") as f:
        f.write(content)
    print(f"Wrote glossary skill to {args.output}")
    print("Review it, then install via `databricks workspace import-dir` and start a NEW chat.")


if __name__ == "__main__":
    main()
